### PR TITLE
use renamed dom.el => doom.el, and other fixes

### PR DESCRIPTION
**Pull request by tarsius**
See https://github.com/toroidal-code/dom.el/issues/2.

### CODE REVIEW

**Comment by 8cylinder** [comment]
You. are. awesome.  Thank you.

**Comment by tarsius** [comment]
You are welcome. By the way, I got carried away and also did some code cleanup. Do you want me to create a pr for that?

**Comment by 8cylinder** [comment]
Whichever is easiest for you.  I also added you as as contributor so you
can directly commit if that is any easier.

Getting a fresh look at some dusty code is awesome.

Thanks again!

**Comment by tarsius** [comment]
> Whichever is easiest for you.

I've created a pr. Make sure to review before merging, just to make sure.

> I also added you as as contributor so you can directly commit if that is any easier.

I do not intend to work anymore on this. Please remove my permissions again.

> Getting a fresh look at some dusty code is awesome.

You are welcome.

**Pull request merged**
